name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v5

      - name: ğŸ­ Use Node.js
        uses: actions/setup-node@v4

      - name: ğŸ“¥ Install Web
        run: npm install

      - name: ğŸ‘¾ Audit Web
        run: npm audit --audit-level=low

      - name: ğŸ”¨ Build
        run: npm run build

  Server:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v5

      - name: ğŸ­ Use Node.js
        uses: actions/setup-node@v4

      - name: ğŸ“¥ Install Web
        run: npm install

      - name: ğŸ® Start server
        run: npm run test
